name: Compile push_obj_into_mesh.exe with MinGW-GCC

on:
  push

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Mingw64
      run: echo "C:\tools\mingw64\bin" >> $env:GITHUB_PATH
      shell: pwsh
    
    - name: Compile C code
      run: |         
         cd ./src/C
         ls
         gcc push_obj_into_mesh.c -o push_obj_into_mesh.exe -static -lm 
         cd ../..
         ls
         Move-Item -Path "src/C/push_obj_into_mesh.exe" -Destination "Utils/"
    
    - name: Create branch and commit changes
      run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git checkout ${{ github.ref_name }}
         git add .
         git commit -m 'Compile push_obj_into_mesh.exe with static libraries'

    - name: Push changes
      run: git push origin ${{ github.ref_name }}
