name: Compile push_obj_into_mesh.exe with MinGW-GCC
on:
  push
permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Compile C code    
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd src\C
        dir
        cl push_obj_into_mesh.c /Fe:push_obj_into_mesh.exe /link /out:push_obj_into_mesh.exe
        cd ..\..
        dir
        move src\C\push_obj_into_mesh.exe Utils\
      shell: cmd
    
    - name: Create branch and commit changes
      run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git checkout ${{ github.ref_name }}
         git add .
         git commit -m 'Compile push_obj_into_mesh.exe with Visual Studio'
    - name: Push changes
      run: git push origin ${{ github.ref_name }}
