name: Compile push_obj_into_mesh.exe with MinGW-GCC

on:
  push

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LLVM + LLVM-MinGW
      shell: cmd
      run: |
        set LLVM_DIR=C:\llvm-mingw
        mkdir %LLVM_DIR%
        curl -L -o %LLVM_DIR%\llvm-mingw.zip https://github.com/mstorsjo/llvm-mingw/releases/download/20260421/llvm-mingw-20260421-msvcrt-x86_64.zip
        powershell -Command "Expand-Archive %LLVM_DIR%\llvm-mingw.zip -DestinationPath %LLVM_DIR%"
        echo %LLVM_DIR%\llvm-mingw-20260421-msvcrt-x86_64\bin>>%GITHUB_PATH%

    - name: Compile C code with Clang (LLVM-MinGW)
      shell: cmd
      run: |
        cd src\C
        clang --target=x86_64-w64-windows-gnu push_obj_into_mesh.c -o push_obj_into_mesh.exe -static -lm
        cd ..\..
        move src\C\push_obj_into_mesh.exe Utils\

    - name: Cleanup LLVM
      shell: cmd
      run: |
        rmdir /s /q C:\llvm-mingw

    - name: Create branch and commit changes
      run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git checkout ${{ github.ref_name }}
         git add .
         git commit -m 'Compile push_obj_into_mesh.exe with static libraries'

    - name: Push changes
      run: git push origin ${{ github.ref_name }}
