name: Update nvcompress 1.30

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download nvcompress
      run: |
        mkdir -p temp/win
        mkdir -p temp/lin
        mkdir -p temp/lin_arm
        mkdir -p temp/mac
        wget https://github.com/w8sl/nvidia-texture-tools/releases/download/09.04.2025/nvtt-macos-latest.zip -O temp/mac/nvtt-macos-latest.zip
        wget https://github.com/w8sl/nvidia-texture-tools/releases/download/09.04.2025/nvtt-windows-latest.zip -O temp/win/nvtt-windows-latest.zip
        wget https://github.com/w8sl/nvidia-texture-tools/releases/download/09.04.2025/nvtt-ubuntu-22.04-arm.zip -O temp/lin_arm/nvtt-ubuntu-22.04-arm.zip
        wget https://github.com/w8sl/nvidia-texture-tools/releases/download/09.04.2025/nvtt-ubuntu-22.04.zip -O temp/lin/nvtt-ubuntu-22.04.zip
        unzip temp/mac/nvtt-macos-latest.zip -d temp/mac/
        unzip temp/win/nvtt-windows-latest.zip -d temp/win/
        unzip temp/lin_arm/nvtt-ubuntu-22.04-arm.zip -d temp/lin_arm/
        unzip temp/lin/nvtt-ubuntu-22.04.zip -d temp/lin/
        
        cd temp
        ls -R
        cd ..
        
    - name: Make dirs
      run: |      
        mkdir -p Utils/nvcompress/new/lin/aarch64
        mkdir -p Utils/nvcompress/new/win
        mkdir -p Utils/nvcompress/new/mac/arm64

    - name: Rename and move nvcompress
      run: |
        mv temp/lin_arm/nvtt-ubuntu-22.04-arm/bin/nvcompress Utils/nvcompress/new/lin/aarch64/
        mv temp/lin/nvtt-ubuntu-22.04/bin/nvcompress Utils/nvcompress/new/lin/
        mv temp/mac/nvtt-macos-latest/bin/nvcompress Utils/nvcompress/new/mac/arm64    
        mv temp/win/nvtt-windows-latest/bin/nvcompress.exe Utils/nvcompress/new/win/

    - name: Remove temp directory
      run: rm -rf temp/*
    
    - name: Create branch and commit changes
      run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git checkout ${{ github.ref_name }}
         git add .
         git commit -m 'Update nvcompress'

    - name: Push changes
      run: git push origin ${{ github.ref_name }}
